/**
 * Proactive behaviour, scheduled entirely locally.
 *
 * AURA speaking up on her own is the single most spam-prone feature in the
 * product, so the rules here are conservative by construction: a randomised
 * interval inside the user's bounds, quiet hours honoured, one line per firing,
 * and no line ever generated by an API call. Nothing in this file costs credit.
 */

import type { ActiveApp, Settings } from "@/types";
import { QuoteRotation } from "./quotes";

export type ProactiveKind = "greeting" | "break" | "app" | "quote" | "late" | "idle";

export interface ProactiveLine {
  text: string;
  kind: ProactiveKind;
}

export interface ProactiveHandlers {
  /** Deliver a line. The host decides bubble vs. notification. */
  speak: (line: ProactiveLine) => void;
  /** Whether the user is currently interacting; suppresses interruptions. */
  isBusy: () => boolean;
}

const GREETINGS: Record<string, string[]> = {
  morning: [
    "Morning. Ready to pretend we're going to be productive?",
    "Morning. The day is still theoretical at this point.",
    "You're up. I'll take that as ambition.",
  ],
  afternoon: [
    "Afternoon. Still standing, I see.",
    "Halfway. Statistically the day improves from here.",
  ],
  evening: [
    "Evening. Winding down, or pretending to?",
    "Evening. Whatever it was, it's mostly behind you now.",
  ],
  night: [
    "It's getting late.",
    "Late. Whatever you're fixing will still be broken tomorrow.",
    "This is the hour where bugs get written, not fixed.",
  ],
};

const BREAKS = [
  "You've been at this a while. Break?",
  "Ninety minutes without moving. Stand up, at minimum.",
  "Take ten. Just don't turn ten minutes into two hours.",
  "Your focus is fine. Your posture isn't.",
];

const APP_LINES: Record<string, string[]> = {
  editor: ["Back to coding?", "The editor's open. That's usually a good sign.", "Ah. Real work."],
  browser: [
    "Another browser tab. Bold strategy.",
    "Research, or 'research'?",
    "The browser again. I won't ask.",
  ],
  terminal: ["Terminal's open. Something's about to happen.", "Shell time. Try not to rm anything important."],
  media: ["Good choice. Background noise helps.", "Music on. That usually means focus or avoidance."],
  games: ["Well. That's one way to spend the evening.", "Games. I'll allow it."],
  social: ["Chat's open. Ten minutes, we both know it won't be."],
  documents: ["Documents. My condolences."],
  design: ["Design work. That's the fun kind of difficult."],
};

const IDLE_LINES = [
  "Still here when you need me.",
  "Quiet out there.",
  "I'll be here.",
];

const pick = <T,>(items: T[]): T =>
  items[Math.floor(Math.random() * items.length)] as T;

function timeBucket(hour: number): keyof typeof GREETINGS {
  if (hour >= 5 && hour < 12) return "morning";
  if (hour < 17) return "afternoon";
  if (hour < 22) return "evening";
  return "night";
}

/** True when `hour` falls inside a possibly-wrapping quiet-hours window. */
export function inQuietHours(hour: number, start: number, end: number): boolean {
  if (start === end) return false;
  return start < end ? hour >= start && hour < end : hour >= start || hour < end;
}

export class ProactiveScheduler {
  private settings: Settings;
  private handlers: ProactiveHandlers;
  private timer: number | null = null;
  private quoteTimer: number | null = null;
  private quotes = new QuoteRotation();

  private sessionStart = Date.now();
  private lastBreakNudge = 0;
  private greetedOn: string | null = null;
  private activeApp: ActiveApp | null = null;
  private disposed = false;

  constructor(settings: Settings, handlers: ProactiveHandlers) {
    this.settings = settings;
    this.handlers = handlers;
  }

  start(): void {
    this.scheduleNext();
    this.scheduleQuote();
  }

  update(settings: Settings): void {
    const intervalChanged =
      settings.proactiveMinMinutes !== this.settings.proactiveMinMinutes ||
      settings.proactiveMaxMinutes !== this.settings.proactiveMaxMinutes ||
      settings.proactiveEnabled !== this.settings.proactiveEnabled;
    const quotesChanged =
      settings.quotesEnabled !== this.settings.quotesEnabled ||
      settings.quoteIntervalMinutes !== this.settings.quoteIntervalMinutes;

    this.settings = settings;
    if (intervalChanged) this.scheduleNext();
    if (quotesChanged) this.scheduleQuote();
  }

  /**
   * Keep track of the foreground app so scheduled lines can refer to it.
   * Reacting to the *switch* itself belongs to the reaction system in
   * `reactions.ts`, which has the activity context to do it well.
   */
  setActiveApp(app: ActiveApp | null): void {
    this.activeApp = app;
  }

  /** Called when the user interacts, to push the next interruption out. */
  noteInteraction(): void {
    this.sessionStart = Date.now();
    this.scheduleNext();
  }

  /** The greeting shown when AURA first appears, at most once per calendar day. */
  greeting(): ProactiveLine | null {
    if (!this.settings.greetingOnStart) return null;
    const today = new Date().toDateString();
    if (this.greetedOn === today) return null;
    this.greetedOn = today;
    const bucket = timeBucket(new Date().getHours());
    return { text: pick(GREETINGS[bucket]!), kind: "greeting" };
  }

  dispose(): void {
    this.disposed = true;
    if (this.timer !== null) window.clearTimeout(this.timer);
    if (this.quoteTimer !== null) window.clearTimeout(this.quoteTimer);
    this.timer = null;
    this.quoteTimer = null;
  }

  /** True while quiet hours are in effect. Also gates live app reactions. */
  isQuiet(): boolean {
    if (!this.settings.quietHoursEnabled) return false;
    return inQuietHours(
      new Date().getHours(),
      this.settings.quietHoursStart,
      this.settings.quietHoursEnd,
    );
  }

  private scheduleNext(): void {
    if (this.timer !== null) window.clearTimeout(this.timer);
    this.timer = null;
    if (this.disposed || !this.settings.proactiveEnabled) return;

    const min = this.settings.proactiveMinMinutes * 60_000;
    const max = Math.max(min, this.settings.proactiveMaxMinutes * 60_000);
    const delay = min + Math.random() * (max - min);

    this.timer = window.setTimeout(() => this.fire(), delay);
  }

  private scheduleQuote(): void {
    if (this.quoteTimer !== null) window.clearTimeout(this.quoteTimer);
    this.quoteTimer = null;
    if (this.disposed || !this.settings.quotesEnabled) return;

    // Jitter so quotes and proactive lines don't land together every time.
    const base = this.settings.quoteIntervalMinutes * 60_000;
    const delay = base * (0.7 + Math.random() * 0.6);

    this.quoteTimer = window.setTimeout(() => {
      if (!this.isQuiet() && !this.handlers.isBusy()) {
        const quote = this.quotes.next();
        this.handlers.speak({ text: quote.text, kind: "quote" });
      }
      this.scheduleQuote();
    }, delay);
  }

  private fire(): void {
    this.scheduleNext();
    if (this.disposed || !this.settings.proactiveEnabled) return;
    if (this.isQuiet() || this.handlers.isBusy()) return;

    this.handlers.speak(this.chooseLine());
  }

  private chooseLine(): ProactiveLine {
    const now = Date.now();
    const hour = new Date().getHours();
    const focusedFor = now - this.sessionStart;

    // A long unbroken stretch is the one thing worth interrupting for.
    if (focusedFor > 90 * 60_000 && now - this.lastBreakNudge > 90 * 60_000) {
      this.lastBreakNudge = now;
      return { text: pick(BREAKS), kind: "break" };
    }

    if (hour >= 23 || hour < 3) {
      return { text: pick(GREETINGS.night!), kind: "late" };
    }

    const app = this.activeApp;
    if (app && APP_LINES[app.category] && Math.random() < 0.4) {
      return { text: pick(APP_LINES[app.category]!), kind: "app" };
    }

    if (Math.random() < 0.55) {
      return { text: this.quotes.next().text, kind: "quote" };
    }

    return { text: pick(IDLE_LINES), kind: "idle" };
  }
}
